Refactored

diff --git a/getpasswords b/getpasswords
--- a/getpasswords
+++ b/getpasswords
@@ -15,65 +15,60 @@ lastpassOffsetX=25
 lastpassOffsetY=45
 passwordOffsetX=-50
 passwordOffsetY=70
-termString="s@"
-# If we were in a terminal, user ctrl+shift+v to paste, otherwise use ctrl+v
-#if [[ $(xdotool getwindowname $currentWid) == *"${termString}"* ]]
-#then
-  pasteCommand=ctrl+shift+v
-#else
-#  pasteCommand=ctrl+v
-#fi
 ### End configuration ###
 
-sleep 0.5
+searchTerm=$1
+mouseMode=$2
 
-# Accepts the password to search for in LastPass
-if [[ -z $1 ]]
-then
-  echo "A search term is required."
-  exit 1
-else
-  searchTerm=$1
-fi
+function errorCheck {
+  if [[ -z $searchTerm ]]; then
+    echo "A search term is required."
+    exit 1
+  fi
+}
 
-mode=$2
+function setMouseMode {
+  [[ "$mouseMode" == "left" ]] && buttonRight=1 || buttonRight=3
+  [[ "$mouseMode" == "left" ]] && buttonLeft=3 || buttonLeft=1
+}
 
-if [[ "$mode" == "left" ]]
-then
-  buttonRight=1
-  buttonLeft=3
-else
-  buttonRight=3
-  buttonLeft=1
-fi
+function getCurrentWindowInfo {
+  currentWid=$(xdotool getactivewindow)
+  browserWid=$(xdotool search "${browserClassName}" | head -1)
+}
 
-# Gets the current window and the browser window
-currentWid=$(xdotool getactivewindow)
-browserWid=$(xdotool search "${browserClassName}" | head -1)
+function calculateCoordinates {
+  eval $(xdotool getwindowgeometry --shell $browserWid)
+  browserMouseX=$((X + WIDTH - lastpassOffsetX))
+  browserMouseY=$((Y + lastpassOffsetY))
+}
 
-# Makes the geometry and postion of the browser window available in this script
-eval $(xdotool getwindowgeometry --shell $browserWid)
+function activateLastpass {
+  xdotool windowactivate --sync $browserWid
+  sleep 0.1
+  xdotool mousemove --sync --clearmodifiers $browserMouseX $browserMouseY click $buttonLeft
+  sleep 0.1
+}
 
-# Calculates the mouse coordinates
-browserMouseX=$((X + WIDTH - lastpassOffsetX))
-browserMouseY=$((Y + lastpassOffsetY))
+function copyPassword {
+  xdotool type --clearmodifiers "$searchTerm"
+  sleep 0.1
+  xdotool mousemove_relative --sync --clearmodifiers -- $passwordOffsetX $passwordOffsetY click $buttonRight
+  sleep 0.1
+  xdotool key --clearmodifiers Down Down Down Return
+}
 
-# Activates the browser applet
-xdotool windowactivate --sync $browserWid
-sleep 0.1
-xdotool mousemove --sync --clearmodifiers $browserMouseX $browserMouseY click $buttonLeft
-sleep 0.1
+function pastePassword {
+  # Go back to the previous window
+  xdotool windowactivate --sync $currentWid
+  # Paste the password and press enter
+  xdotool key --clearmodifiers --delay 50 ctrl+shift+v Return
+}
 
-# Gets the password
-
-xdotool type --clearmodifiers "${searchTerm}"
-sleep 0.1
-xdotool mousemove_relative --sync --clearmodifiers -- $passwordOffsetX $passwordOffsetY click $buttonRight
-sleep 0.1
-xdotool key --clearmodifiers Down Down Down Return
-
-# Go back to the previous window
-xdotool windowactivate --sync $currentWid
-
-# Paste the password and press enter
-xdotool key --clearmodifiers --delay 50 $pasteCommand Return
+errorCheck
+setMouseMode
+getCurrentWindowInfo
+calculateCoordinates
+activateLastpass
+copyPassword
+pastePassword
